Async program
etbox/NodeJS pull request #5
Opened 2019-03-13 09:43 UTC by etbox

2019-03-13 11:04 UTC, vincent-ng requested changes
3种实现，都各有各的方式可以把找到的number返回给调用者的。
可以再思考一下

2019-03-13 11:04 UTC, vincent-ng commented on task5/task5-client-callback.js
> +			sendRequest()
guessNum可以作为参数传给sendRequest

2019-03-14 06:02 UTC, vincent-ng requested changes
重构一下代码
1. 多余的注释，删掉
2. 多余的全局变量，删掉
3. 三个程序写成统一的函数参数和返回值
    1. 输入的参数是：搜索范围（callback style的callback也作为参数）
    2. 输出是最终结果

2019-03-14 07:44 UTC, vincent-ng requested changes

2019-03-14 07:44 UTC, vincent-ng commented on task5/task5-client-callback.js
> +function sendRequest(floor, ceil, guessNum) {
第三个参数可以去掉的

2019-03-14 07:44 UTC, vincent-ng commented on task5/task5-client-callback.js
> +		callback(floor, ceil, Math.floor((floor + ceil) / 2)) // callback形式无法返回最终值，除非使用全局变量或者传递的参数为对象
callback style也是可以返回最后的值的，不需要全局变量。
思考一下怎么实现。

2019-03-14 07:44 UTC, vincent-ng commented on task5/task5-client-promise.js
> +function sendRequest(floor, ceil, guessNum) {
第三个参数可以去掉

2019-03-14 12:24 UTC, vincent-ng requested changes
逻辑基本上没问题了。
剩下就是error的处理。每种style有不同的error处理方式。这部分还需优化

2019-03-14 12:24 UTC, vincent-ng commented on task5/task5-client-callback.js
> +			throw Error(body)
这里throw error，不妥。调用者并不能捕获到这个错误的

2019-03-14 12:24 UTC, vincent-ng commented on task5/task5-client-promise.js
> +		.catch(err => console.log(err))
这里的catch是没有意义的，反而会让调用者不知道出现了错误

2019-03-15 11:14 UTC, vincent-ng requested changes

2019-03-15 11:14 UTC, vincent-ng commented on task5/task5-client-async.js
> +		return sendRequest(guessNum, ceil)
漏了await了
下同

2019-03-15 11:14 UTC, vincent-ng commented on task5/task5-client-callback.js
> +			callback(body)
```javascript
callback(new Error(body))
```

2019-03-15 11:14 UTC, vincent-ng commented on task5/task5-client-callback.js
> +			console.log(err)
1. 这里throw 然后自己catch error是意义不大的。等价于直接在throw的地方console.log
2. 调用者给了你callback，但它并不能拿到这个函数的error，因为你自己处理了

2019-03-15 11:14 UTC, vincent-ng commented on task5/task5-client-callback.js
> +				sendRequest(floor, ceil, callback) // 最内层的错误会由callback进行处理，不会抛到本层
一般来说，如果一个函数声明为callback style的话，意味着调用者不需要try catch来捕获错误，所有错误均会通过callback来返回给调用者。

2019-03-18 02:52 UTC, etbox commented on task5/task5-client-async.js
> +		return sendRequest(guessNum, ceil)
return await 的值会将返回值再次封装为 promise

2019-03-18 02:59 UTC, vincent-ng approved these changes

2019-03-18 03:02 UTC, merged